# File location: sudo vim /etc/confd/conf.d/haproxy.toml

[template]
prefix = "apps"
src = "haproxy.cfg.tmpl"
dest = "/etc/haproxy/haproxy.cfg"
keys = [
"perpool-wordpress-80",
]
reload_cmd = "/usr/sbin/service haproxy reload"
